@extends('layouts.user_type.auth-app')
@section('content')
    {{-- print_r($data) --}}

    <div class="main-content">
        <div class="page-content">
            <div class="container-fluid">
                <div class="card">
                    <div class="card-header">
                        <h6 class="font-weight-bolder mb-0">Two Factor Authentication</h6>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">

                                <div class="card">
                                    <div class="card-header pb-0">
                                        <h6>Step 1: Download an authentication app for our mobile device</h6>
                                    </div>
                                    <div class="card-body">
                                        <form class="row g-3">
                                            <div class="col-md-6">
                                                <p>1. Install <a href="https://en.wikipedia.org/wiki/Google_Authenticator"
                                                        target="_blank" style="font-size:16px; color: ">Google
                                                        Authenticator</a> on your
                                                    mobile device.</p>

                                                <div>
                                                    <a href="https://apps.apple.com/us/app/google-authenticator/id388497605"
                                                        target="_blank"><img src="{{ asset('images/ios.png') }}"
                                                            width="128px"></a>
                                                    <span>&nbsp;</span>
                                                    <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en&gl=US"
                                                        target="_blank"><img src="{{ asset('images/android.png') }}"
                                                            width="128px"></a>

                                                </div>

                                            </div>

                                        </form>
                                    </div>
                                </div>

                                <div class="card">
                                    <div class="card-header pb-0">
                                        <h6>Step 2: Scan the barcode or enter the key code in your authenticator app</h6>
                                    </div>
                                    <div class="card-body">
                                        <form class="row g-3">
                                            <div class="col-md-6">
                                                <p>Open your authenticator app and use your mobile device's camera to scan
                                                    the QR code
                                                    below.
                                                </p>
                                                Your secret code is : <b id="secretecode"></b>
                                                <div class="my-qr" id="myqrcode">

                                                </div>

                                            </div>
                                        </form>
                                    </div>
                                </div>

                                <div class="card">
                                    <div class="card-header pb-0">
                                        <div class="row">
                                            <div class="col-md-9">
                                                <h6>Step 3: Enter the six-digit token generated by your app</h6>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        <form class="g-3">
                                            <div class="row">
                                                <div class="col-md-8 row">
                                                    <div class="col-md-7">
                                                        <p>Enter the six-digit token generated by your app</p>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <div class="input-group float-right">
                                                            <span id="g2fa-status"
                                                                class="input-group-text @if ($data['google2fa_status'] == 'disable') text-danger   @else text-success" @endif">Two
                                                                Factor Auth
                                                                {{ ucfirst($data['google2fa_status']) }}d.</span>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-md-6">
                                                    <label>Token</label>
                                                    <div class="input-group">
                                                        <span class="input-group-text">
                                                            <img src="{{ asset('images/email-vector.png') }}"
                                                                width="25">
                                                        </span>

                                                        <input type="text" name="token" class="form-control "
                                                            placeholder="Enter Token" id="otp-input">

                                                    </div>

                                                </div>
                                                <div class="col-md-2 mt-2">

                                                    <button onclick="sendOTP()" type="button"
                                                        class="btn btn-warning mt-4" id="fastatusChkOtpButton">

                                                        <i id="buttontext"></i>

                                                    </button>

                                                </div>

                                                <div class="col-md-2 mt-2" id="reset-button-container">

                                                    <button id="reset-button" type="button"
                                                        class="btn btn-primary mt-4"
                                                        @if ($data['google2fa_status'] == 'disable') style="opacity:0.5; cursor:text"   @else onclick="reset2FA_Action()" @endif>Reset
                                                        G2FA</button>

                                                </div>

                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <div class="modal fade" id="editBankDetailsmodal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Enter OTP</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"
                        onclick="closeModal('editBankDetailsmodal')"></button>
                </div>
                <div class="modal-body">
                    <div class="row align-items-center justify-content-center">
                        <div class="col-md-4">
                            <img src="{{ asset('images/email-vector.png') }}" class="img-fluid">
                        </div>
                        <div class="col-md-8">
                            <div class="row">
                                <div class="col-md-12">
                                    <input type="text" name="otp" class="form-control w1000" placeholder="Enter OTP"
                                        v-model="otp_reset" id="pass-otp" maxlength="6"
                                        onkeypress="return (event.charCode == 8 || event.charCode == 0 || event.charCode == 13) ? null : event.charCode >= 48 && event.charCode <= 57">
                                    <!-- <span class="error-msg-size tooltip-inner text-white">OTP sent to {{ Auth::user()->email }}</span> -->

                                    <span class="error-msg-size tooltip-inner text-white">OTP sent to
                                        @php
                                            $email = Auth::user()->email;
                                            $modifiedEmail = substr_replace($email, '********', 4, 8); // Add an asterisk after the fourth character
                                        @endphp

                                        {{ $modifiedEmail }}
                                    </span>



                                    <!-- <input type="text" class="form-control" placeholder="Enter OTP"> -->
                                </div>
                                <div class="col-md-12 text-center mt-3">
                                    <button type="button" class="btn bg-gradient-primary"
                                        onclick="sendOTP()">Resend</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button onclick="resetG2fa()" type="button" class="btn btn-primary kbb-bbt">Submit</button>
                    <!-- <button type="button" class="btn btn-light">Submit</button> -->
                </div>
            </div>
        </div>
    </div>



    </div>



    <script>
        var fastatus = "";
        var profile;

        function getProfileInfo() {
            $(".load").hide();
            $(".loadUpdate").hide();
            // axios.post('./get-profile-info', {})
            //   .then(function(response) {
            //     var profile = response.data.data;
            //     var fastatus = profile.google2fa_status;

            //     if(fastatus == "disable")
            //     {
            //         var div = '<div class="my-qr"><div><img v-bind:src="'+profile.QR_Image+'" width="100"></div></div>';
            //     }
            //     else{
            //        var div = '';
            //     }

            //     $("#fastatus");.text(div);


            //   })
            //   .catch(function(error) {
            //     console.log(error);
            //   });


            var csrf_token = $('meta[name="csrf-token"]').attr('content');
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': csrf_token
                }
            });



            $.ajax({
                type: 'POST',
                url: "{{ url('/get-profile-info') }}",
                data: {},
                success: function(response) {
                    profile = response.data;
                    fastatus = profile.google2fa_status;
                    //alert(fastatus);
                    if (fastatus == "disable") {

                        const div = document.getElementById("myqrcode");
                        div.innerHTML = profile.QR_Image;

                        document.getElementById("secretecode").innerHTML = profile.secret;
                        document.getElementById("fastatusChkOtpButton").innerHTML = "Enable";


                    } else {
                        var div = '';
                        document.getElementById("fastatusChkOtpButton").innerHTML = "Disable";
                    }

                    // $("#fastatus").text(div);
                },
                error: function(error) {
                    console.log(error);
                }
            });

        }


        function sendOTP() {

            if ($('#otp-input').val() != "" && $('#otp-input').val().length >= 6) {
                if (fastatus == "enable") {
                    resetG2fa();
                    return false;
                }
                var csrf_token = $('meta[name="csrf-token"]').attr('content');
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': csrf_token
                    }
                });
                $.ajax({
                    url: 'sendOtp-update-user-profile',
                    type: 'POST',
                    success: function(response) {
                        if (response.code == 200) {
                            toastr.success(response.message);

                            $('#editBankDetailsmodal').modal('show');
                        } else {
                            toastr.error(response.message);
                        }
                    },
                    error: function(error) {
                        console.log(error);
                    }
                });
            } else {
                toastr.error("Please Enter TOKEN First");
            }

        }


        function sendotpforresset2fa() {

            // if($('#otp-input').val() != "" && $('#otp-input').val().length >= 6)
            // {
            if (fastatus == "enable") {
                resetG2fa();
                return false;
            }
            var csrf_token = $('meta[name="csrf-token"]').attr('content');
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': csrf_token
                }
            });
            $.ajax({
                url: 'sendOtp-update-user-profile',
                type: 'POST',
                success: function(response) {
                    if (response.code == 200) {
                        toastr.success(response.message);

                        $('#editBankDetailsmodal').modal('show');
                    } else {
                        toastr.error(response.message);
                    }
                },
                error: function(error) {
                    console.log(error);
                }
            });


        }



        function resetG2fa() {

            var csrf_token = $('meta[name="csrf-token"]').attr('content');
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': csrf_token
                }
            });

            $.ajax({
                url: "{{ url('/reset-g2fa-user') }}",
                type: 'POST',
                data: {
                    otp: $('#pass-otp').val(),
                    google2fa_secret: profile.secret
                },
                success: function(response) {
                    if (response.code == 200) {
                        $('#editBankDetailsmodal').modal('hide');
                        toastr.success(response.message);
                        var urlforredirect = "{{ url('/google2fa') }}";


                        setTimeout(function() {
                            //location.reload();

                            window.location.href = urlforredirect;
                        }, 50);

                    } else if (response.code == 401) {
                        toastr.error(response.message);
                        localStorage.removeItem('user-token');
                        localStorage.removeItem('check-in');
                        location.reload();
                    } else {
                        toastr.error(response.message);
                    }
                },
                error: function(error) {
                    console.log(error);
                }
            });
        }



        function validateGoogle2Fa() {
            $(".load").show();
            $(".sub").hide();
            var status = '';
            if (fastatus === 'disable') {
                status = 'enable';
            } else if (fastatus === 'enable') {
                status = 'disable';
            }

            var csrf_token = $('meta[name="csrf-token"]').attr('content');
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': csrf_token
                }
            });

            $.ajax({
                url: "{{ url('/2fa/validate') }}",
                type: 'POST',
                data: {
                    googleotp: $('#otp-input').val(),
                    secret: profile.secret,
                    status: status
                },
                success: function(response) {
                    if (response.code == 200) {
                        $(".load").hide();
                        $(".sub").show();
                        fastatus = profile.google2fa_status;

                        /*  $('#editBankDetailsmodal').modal('hide');
                            this.otpstatus = true;*/
                        $('#editBankDetails1').modal('hide');
                        // $('#editBankDetailsmodal').modal('toggle');
                        //$('#editBankDetailsmodal').modal('hide');
                        //this.readProfile();
                        toastr.success(response.message);
                        //this.otp = ''
                    } else {
                        $(".load").hide();
                        $(".sub").show();
                        toastr.error(response.message);
                        otp = '';
                    }
                },
                error: function(error) {
                    $(".load").hide();
                    $(".sub").show();
                }
            });
        }



        function reset2FA_Action() {

            var csrf_token = $('meta[name="csrf-token"]').attr('content');
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': csrf_token
                }
            });

            $.ajax({
                url: "{{ url('/send-g2fa-reset-link') }}",
                type: 'POST',
                data: {
                    //otp: $('#pass-otp').val(),
                    google2fa_secret: profile.secret
                },
                success: function(response) {

                    console.log(response);
                    if (response.code == 200) {
                        // $('#editBankDetailsmodal').modal('hide');
                        toastr.success(response.message);

                    } else if (response.code == 401) {
                        toastr.error(response.message);

                    } else {
                        toastr.error(response.message);
                    }
                },
                error: function(error) {
                    console.log(error);
                }
            });



        }
        getProfileInfo();


        var token = "{{ $data['token'] }}";
        //alert(token)
        if (token != '') {
            sendotpforresset2fa();
        }
    </script>
@endsection
